INTERACTIVE_MODELS_PATH: "experiments/sbd/"
EXPS_PATH: "experiments"

# Evaluation datasets
GRABCUT_PATH: "datasets/TestSet/GrabCut"
BERKELEY_PATH: "datasets/TestSet/Berkeley"
DAVIS_PATH: "datasets/TestSet/DAVIS"
COCO_MVAL_PATH: "datasets/TestSet/COCO_MVal"
COCO_MVAL_SEEN_PATH: "datasets/TestSet/COCO_MVal_seen"
COCO_MVAL_UNSEEN_PATH: "datasets/TestSet/COCO_MVal_unseen"

# Train datasets
SBD_PATH: "datasets/SBD"
COCO_PATH: "datasets/coco2017"
LVIS_PATH: "datasets/LVIS/label"
OPENIMAGES_PATH: "datasets/OpenImages"
PASCALVOC_PATH: "datasets/TestSet/VOC2012"

ADE20K_PATH: "datasets/ADE20K"

# You can download the weights for HRNet from the repository:
# https://github.com/HRNet/HRNet-Image-Classification
IMAGENET_PRETRAINED_MODELS:
  HRNETV2_W18: "pretrained_models/hrnetv2_w18_imagenet_pretrained.pth"
  HRNETV2_W32: "pretrained_models/hrnetv2_w32_imagenet_pretrained.pth"
  HRNETV2_W40: "pretrained_models/hrnetv2_w40_imagenet_pretrained.pth"
  HRNETV2_W48: "pretrained_models/hrnetv2_w48_imagenet_pretrained.pth"
